## введение 
Что, зачем и почему.
GUIs

## простые вычисления

```{r}
log(10)

```
## простые функции log, sum, exp...

## `?` справка по функциям

## назначение объектов
```{r}

A<-2+3 # складываем и создаем А
A^2

A <- 3.14
```
## операции с объектами
```{r}
A

A+10
A^2
sqrt(A)

A^0.5

A^(1/2)

rm(A)

A
```
## вектор, конкатенация
```{r}
B<-c(1,21,31,5) # создаем вектор
```
## subsetting vector
```{r}
B*2

B[1] # первый элемент из B

B[B>10]

B[B>=10]
B[B==10]
B[B!=10]

C<-B[B!=10]

B[1]<-6

B<-c(B,6)

B[1:3]

1:5

B<-B[1:3]
B<-B[-4]


B<-c(B[1:3], 6, B[4:length(B)])

B<-B[-1]

rnorm(98, 50, 10)
Tail<-rnorm(n=98, mean=50, sd=10)
?rnorm

```
## гистограмма, статистика вектора
```{r}
hist(Tail, breaks=20)

mean(Tail)
sd(Tail)
median(Tail)
summary(Tail)
```
## data.frame
```{r}

Swifts<-data.frame(
     Tail=c(rnorm(98, 50, 10), rnorm(67, 40, 10)),
	 Sex=c(rep('Male', 98), rep('Female', 67)))
```
## subsetting
```{r}
head(Swifts, 10)
tail(Swifts)
str(Swifts)

Swifts[1,] # первая строка
Swifts[,2] # вторая колонка

Swifts[1:10, 2]
Swifts$Sex 
Swifts$Tail 
Swifts$Tail>50
Swifts[Swifts$Tail>50,]
subset(Swifts, Tail>50)
```