# План занятий
## 1. Основы работы с R
Принципы работы, симуляция данных /Introduction to R environment and GUIs (RStudio), Introduction to R language. Data simulation.

## 2. Импорт данных
Data import, Objects in R. vector, data.frame, matrix, array, list

## 3. Графики в R
Principles of plotting in R. 

## 4. Линейная регрессия и дисперсионный анализ
Linear regrerssion, ANOVA, Conepts of model selection and multimodel inference.

## 5. Линейная регрессия и дисперсионный анализ, продолжение
Linear regrerssion, ANOVA, Conepts of model selection and multimodel inference.

## 6. Обобщенные линейные модели
GLM (binomial, Poisson). Prediction from GLMs.

## 7. Обобщенные линейные модели, продолжение
GLM (binomial, Poisson). Prediction from GLMs.

## 8. Анализ главных компонент
Principal components.

## 9. Зачёт
Final Exam.

Возможные темы для дополнительных занятий

## GAM Generalised additive models
basic introdution to mgcv

## Псевдорепликация и смешанные модели
Mixed effects models, pseudoreplication.

## Карты в R
Maps in R. Introduction to sp and maptools packages. Some info over ggmap.


